version: "3.8"

services:
  portfolio:
    build:
      context: ./portfolio
    container_name: portfolio-app
    ports:
      - "5000:5000"

  java-app:
    build:
      context: ./samplejavaapp
    container_name: java-app
    ports:
      - "8080:8080"