apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: portfolio
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - portfolio
  selector:
    matchLabels:
      app: portfolio
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
